#!/usr/bin/env python

import sys, getopt, datetime
from PIL import Image
from PIL import ImageChops

def matchTemplate(searchImage, templateImage):
    minScore = -1000
    matching_xs = 0
    matching_ys = 0
    searchImage = searchImage.convert(mode="L")
    templateImage = templateImage.convert(mode="L")
    searchWidth, searchHeight = searchImage.size
    templateWidth, templateHeight = templateImage.size
    templateMask = Image.new(mode="L", size=templateImage.size, color=1)
    for xs in range(searchWidth-templateWidth+1):
        for ys in range(searchHeight-templateHeight+1):
            score = templateWidth*templateHeight
            searchCrop = searchImage.crop((xs,ys,xs+templateWidth,ys+templateHeight))
            diff = ImageChops.difference(templateImage, searchCrop)
            notequal = ImageChops.darker(diff,templateMask)
            countnotequal = sum(notequal.getdata())
            score -= countnotequal

            if minScore < score:
                minScore = score
                matching_xs = xs
                matching_ys = ys

    print "Location=",(matching_xs, matching_ys), "Score=",minScore

def main(argv):
   patternImage = ''
   sourceImage = ''
   try:
      opts, args = getopt.getopt(argv,"p:s:")
   except getopt.GetoptError:
      print './spims -p <FILE> -s <FILE>'
      sys.exit(2)
   for opt, arg in opts:
      if opt == '-p':
         patternImage = Image.open(arg)
         print 'Pattern Image is', arg
         #TODO: Make sure that patternImage is valid
      elif opt == '-s':
         sourceImage = Image.open(arg)
         print 'Source image is', arg
         #TODO: Make sure that sourceImage is valid
   matchTemplate(sourceImage,patternImage)
   print "PROGRAM COMPLETE"

if __name__ == "__main__":
   main(sys.argv[1:])
