#!/usr/bin/perl  
                                                                                                   
if ($#ARGV < 0) {
    error("Usage: ./test <assignment>");
}

foreach $problem (@ARGV) {
    if (! (-e "./problems/$problem")) {
        error("Unable to find tests for '$problem'.");
    }

    if (! (-e "./solutions/$problem")) {
        error("Unable to find reference solution for '$problem'.");
    }

    test($problem);
}

sub trim($){
    my $string = shift;
    $string =~ s/^\s+//;
    $string =~ s/\s+$//;
    return $string;
}

sub clr_line(){
    print "\r";
    print " " x 80;
    print "\r";
}

sub test {
    my ($problem) = @_;

    print "\nTesting $problem:\n";

    my $tests = "./problems/$problem";
    my $solutions = "./solutions/$problem";

    open(my $th, '<:encoding(UTF-8)', $tests)
      or die "Could not open problems file '$tests' $!";

    open(my $sh, '<:encoding(UTF-8)', $solutions)
      or die "Could not open solutions file '$solutions' $!";

    while (my $test = <$th>){
        chomp $test;

        if (my $solution = <$sh>){
            chomp $solution;

            print "[    ] Test: \"\./spims $test\"";  

            my $actual = `../spims $test -t`;
            my $expected = $solution;

            if (trim($actual) eq trim($expected)){
                chomp $actual;
                clr_line();
                print "[PASS] Test: \"\./spims $test\"\n";
                print "       Output: $actual\n\n";
            } else {
                chomp $actual;
                clr_line();
                print "[FAIL] Test: \"\./spims $test\"\n";
                print "       Expected output: $solution\n       Actual output  : $actual\n\n";
                #exit(-1);
            }
        } else {
            warn "Found mismatched test/solution pair!";
        }
    }
}
