#!/usr/bin/perl  
                                                                                                   
if ($#ARGV < 0) {
    error("Usage: ./test <assignment>");
}


foreach $problem (@ARGV) {

    if (! (-e "./problems/$problem")) {
        error("Unable to find tests for '$problem'.");
    }

    if (! (-e "./solutions/$problem")) {
        error("Unable to find reference solution for '$problem'.");
    }

    test($problem);
}

sub test {
    my ($problem) = @_;

    print "Testing $problem\n";

    my $tests = "./problems/$problem";
    my $solutions = "./solutions/$problem";


    open(my $th, '<:encoding(UTF-8)', $tests)
      or die "Could not open file '$tests' $!";

    open(my $sh, '<:encoding(UTF-8)', $solutions)
      or die "Could not open file '$solutions' $!";

    while (my $test = <$th>){
        chomp $test;
        if (my $solution = <$sh>){
            chomp $solution;

            my $actual = `../spims $test`;
            my $expected = $solution;

            if ($actual eq $expected){
                print "[PASS] $test => $solution\n";
            } else {
                print "[FAIL]\n";
                print "    Expected output: $solution\n    Actual output:   $actual\n";
                exit(-1);
            }

        } else {
            warn "Found mismatched test/solution pair!";
        }
        

    }


  
}
